module.exports = {
  help: 'Help',
  organizationName: 'Organization Name',
  personalCenter: 'Personal center',
  logout: 'Sign out',
  de: "'s ",
  confirm: 'Confirm',
  reset: 'Reset',
  copy: 'Copy',
  save: 'Save',
  cancel: 'Cancel',
  showTotal: 'Total {total} ',
  errorNotice: 'get data error',
  saveSuccessNotice: 'Save success',
  prompt: 'Prompt',
  getServicesError: 'Failed to get server resource',
  commonPlaceHolder: (val) => `Please enter ${val}`,
  saveRoleNotice: 'save role error',
  maxPlaceHolder: (val) => `Maximum ${val || 50} characters`,
}
