module.exports = {
  help: '帮助',
  name: '姓名',
  gender: '性别',
  account: '账号',
  email: '邮箱',
  phone: '手机号码',
  organizationName: '组织名称',
  Organization: '所属组织',
  personalCenter: '个人中心',
  logout: '推出登陆',
  save: '保存',
  cancel: '取消',
  confirm: '确定',
  reset: '重置',
  copy: '复制',
  de: '的',
  permission: '权限',
  showTotal: '共 {total} 条',
  errorNotice: '数据获取失败',
  prompt: '提示',
  saveSuccessNotice: '保存成功',
  businessEntity: '业务实体',
  InventoryOrganization: '库存组织',
  getServicesError: '获取服务器失败',
  OrganizationalDataPermissions: '组织数据权限',
  commonPlaceHolder: (val) => `请输入${val}`,
  'roleManagerModule.roleInfo': '角色信息',
  'roleManagerModule.addRole': '新建角色',
  'roleManagerModule.editRole': '编辑角色',
  'roleManagerModule.functionalPermissions': '功能权限',
  'roleManagerModule.dataPermission': '数据权限',
  'roleManagerModule.roleEmployee': '角色员工',
  'roleManagerModule.saveRoleNotice': '保存角色失败',
  'roleManagerModule.roleNamePlaceHolder': '请输入角色名称',
  'roleManagerModule.maxPlaceHolder': (val) => `最多${val || 50}个字符`,
  'roleManagerModule.operationSelectError': '该功能没有被选择，不能配置操作！',
  'roleManagerModule.noOperation': '该功能下没有操作！',
  'roleManagerModule.roleManager': '角色管理',
  'roleManagerModule.isEffect': '请选择是否有效',
  bulkCopyTheCharacterMenu: '确认要批量复制角色菜单嘛?',
  // 字典
  seeAll: '可看所有',
  CanSeeSubordinates: '可看下属',
  justLookAtYourself: '仅看自己',
}
