module.exports = {
  help: '帮助',
  save: '保存',
  cancel: '取消',
  confirm: '确定',
  reset: '重置',
  copy: '复制',
  de: '的',
  showTotal: '共 {total} 条',
  errorNotice: '数据获取失败',
  prompt: '提示',
  saveSuccessNotice: '保存成功',
  getServicesError: '获取服务器失败',
  commonPlaceHolder: (val) => `请输入${val}`,
  saveRoleNotice: '保存角色失败',
  maxPlaceHolder: (val) => `最多${val || 50}个字符`,
}
